name: publish

on:
  push:
    branches:
    - source

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: checkout
      uses: actions/checkout@master
      with:
        ref: source
        token: ${{ secrets.GH_TOKEN }}
    - name: deploy
      run: make deploy-using-docker
      env:
        GIT_AUTHON_NAME: Max Gonzih via GH Actions
        GIT_AUTHOR_EMAIL: gonzih@gmail.com
